version: '3.8'
services:
  dt-herne-wanne-mongodb:
    container_name: dt-herne-wanne-mongodb
    image: mongo:4.4.5
    networks:
      dtHerneNetwork:
        aliases:
          - dt-herne-wanne-database
        ipv4_address: 172.20.0.36
    restart: "always"
  
  dt-herne-wanne-mongo-seed:
    container_name: dt-herne-wanne-mongo-seed
    image: mongo:4.4.5
    # Wait for mongo to initialize, then import data
    # Use the import file for this stack
    entrypoint: [ "bash", "-c", "sleep 20 && sh '/tmp/import.herne-wanne.sh'"]
    networks:
      dtHerneNetwork:
        aliases:
          - dt-herne-wanne-database-seed
        ipv4_address: 172.20.0.35
    depends_on:
      - dt-herne-wanne-mongodb
    volumes:
      # Put json files in this Volume before launching the stack
      - dt-herne-mongodb:/tmp
    restart: "no"
  
  dt-herne-wanne-backend:
    container_name: dt-herne-wanne-backend
    hostname: dt-herne-wanne-backend
    #build: 
    #  context: "DT-Herne-Backend"
    image: t16h05008/dt-herne-wanne-backend:latest
    ports: 
      - 8201:8000
    environment:
      MONGODB_URI: ${MONGODB_URI}
      DB_NAME: ${DB_NAME}
    networks:
      dtHerneNetwork:
        aliases:
          - dt-herne-wanne-backend
        ipv4_address: 172.20.0.34
    restart: "always"
    volumes:
      - dt-herne-backend:/app/data
    depends_on:
      - dt-herne-wanne-mongodb
  
  dt-herne-wanne-frontend:
    container_name: dt-herne-wanne-frontend
    hostname: dt-herne-wanne-frontend
    restart: "always"
    #build: 
    #  context: "DT-Herne-Frontend"
    image: t16h05008/dt-herne-wanne-frontend:latest
    networks:
      dtHerneNetwork:
        aliases:
          - dt-herne-wanne-frontend
        ipv4_address: 172.20.0.33
    ports: 
      - 8200:80
    volumes:
      - dt-herne-frontend-360images:/usr/share/nginx/html/static/images/360deg
      - dt-herne-frontend-videos:/usr/share/nginx/html/static/videos


networks:
  dtHerneNetwork:
    external: true # Network exists even when stack is not running

volumes:
  dt-herne-frontend-360images:
    external: true
  dt-herne-frontend-videos:
    external: true
  dt-herne-backend:
    external: true
  dt-herne-mongodb:
    external: true